# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airbnb_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('survey_id', models.IntegerField(default=0)),
                ('host_id', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('borough', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(max_length=500)),
                ('reviews', models.IntegerField(default=0)),
                ('room_type', models.CharField(max_length=500)),
                ('overall_satisfaction', models.FloatField(default=0)),
                ('accommodates', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('minstay', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('last_modified', models.CharField(max_length=500)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('location', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
