# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_airbnb_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnb_listing',
            name='pub_date',
        ),
    ]
