# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171202_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='elite_years',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
        migrations.DeleteModel(
            name='business',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='checkin',
        ),
        migrations.DeleteModel(
            name='elite_years',
        ),
        migrations.DeleteModel(
            name='friend',
        ),
        migrations.DeleteModel(
            name='hours',
        ),
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='tip',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
