# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171202_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('neighborhood', models.CharField(default=None, max_length=255, null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('postal_code', models.CharField(default=None, max_length=255, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('stars', models.FloatField(default=None, null=True)),
                ('review_count', models.IntegerField(default=None, null=True)),
                ('is_open', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=255, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=255, null=True)),
                ('count', models.IntegerField(default=None, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='elite_years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(default=None, max_length=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(default=None, max_length=255, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('caption', models.CharField(default=None, max_length=255, null=True)),
                ('label', models.CharField(default=None, max_length=255, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(default=None, null=True)),
                ('date', models.DateTimeField(default=None, null=True, verbose_name='date published')),
                ('text', models.TextField()),
                ('useful', models.IntegerField(default=None, null=True)),
                ('funny', models.IntegerField(default=None, null=True)),
                ('cool', models.IntegerField(default=None, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=None, null=True, verbose_name='date published')),
                ('likes', models.IntegerField(default=None, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('review_count', models.IntegerField(default=None, null=True)),
                ('yelping_since', models.DateTimeField(default=None, null=True, verbose_name='date joined')),
                ('useful', models.IntegerField(default=None, null=True)),
                ('funny', models.IntegerField(default=None, null=True)),
                ('cool', models.IntegerField(default=None, null=True)),
                ('fans', models.IntegerField(default=None, null=True)),
                ('average_stars', models.FloatField(default=None, null=True)),
                ('compliment_hot', models.IntegerField(default=None, null=True)),
                ('compliment_more', models.IntegerField(default=None, null=True)),
                ('compliment_profile', models.IntegerField(default=None, null=True)),
                ('compliment_cute', models.IntegerField(default=None, null=True)),
                ('compliment_list', models.IntegerField(default=None, null=True)),
                ('compliment_note', models.IntegerField(default=None, null=True)),
                ('compliment_plain', models.IntegerField(default=None, null=True)),
                ('compliment_cool', models.IntegerField(default=None, null=True)),
                ('compliment_funny', models.IntegerField(default=None, null=True)),
                ('compliment_writer', models.IntegerField(default=None, null=True)),
                ('compliment_photos', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tip',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.user'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.user'),
        ),
        migrations.AddField(
            model_name='elite_years',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.user'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.business'),
        ),
    ]
