# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171202_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='business_id',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='category',
            name='business_id',
            field=models.CharField(max_length=22),
        ),
    ]
